export const MOCK_DASHBOARD_DATA = {
  stats: {
    repository: { stars: 1240, forks: 350 },
    pull_requests: { total: 856, open: 24, closed: 832 },
    issues: { total: 420, open: 45, closed: 375 },
    contributors: { total: 89 },
  },
  contributors: [
    {
      login: 'jdoe',
      avatar_url: 'https://ui-avatars.com/api/?name=John+Doe',
      contributions: 156,
      rank: 1,
      level: 12,
      badges: ['Maintainer', 'Bug Hunter'],
    },
    {
      login: 'asmith',
      avatar_url: 'https://ui-avatars.com/api/?name=Alice+Smith',
      contributions: 142,
      rank: 2,
      level: 11,
      badges: ['Documentation'],
    },
    {
      login: 'bwayne',
      avatar_url: 'https://ui-avatars.com/api/?name=Bruce+Wayne',
      contributions: 98,
      rank: 3,
      level: 9,
      badges: ['Design'],
    },
    {
      login: 'ckent',
      avatar_url: 'https://ui-avatars.com/api/?name=Clark+Kent',
      contributions: 87,
      rank: 4,
      level: 8,
      badges: ['Feature'],
    },
    {
      login: 'pparker',
      avatar_url: 'https://ui-avatars.com/api/?name=Peter+Parker',
      contributions: 65,
      rank: 5,
      level: 7,
      badges: ['Bug Hunter'],
    },
  ],
  activity: Array.from({ length: 12 }).map((_, i) => ({
    week: Math.floor(Date.now() / 1000) - i * 604800,
    total: Math.floor(Math.random() * 50) + 10,
  })),
  mix: [
    {
      name: 'Core Features',
      value: 45,
      count: 450,
      color: '#3B82F6',
      description: 'Main application logic',
    },
    {
      name: 'Documentation',
      value: 25,
      count: 250,
      color: '#10B981',
      description: 'Guides & API docs',
    },
    {
      name: 'Bug Fixes',
      value: 20,
      count: 200,
      color: '#F59E0B',
      description: 'Stability improvements',
    },
    { name: 'Refactor', value: 10, count: 100, color: '#8B5CF6', description: 'Code cleanup' },
  ],
  reviews: {
    top_reviewers: [
      {
        name: 'Reviewer One',
        avatar: 'https://ui-avatars.com/api/?name=Reviewer+One',
        count: 45,
        is_maintainer: true,
      },
      {
        name: 'Reviewer Two',
        avatar: 'https://ui-avatars.com/api/?name=Reviewer+Two',
        count: 32,
        is_maintainer: false,
      },
    ],
    community_happiness: 88,
  },
  graph: { nodes: [], links: [] }, // Simplified for mock
  sunburst: [
    {
      name: 'frontend',
      children: [
        { name: 'components', value: 30 },
        { name: 'pages', value: 20 },
        { name: 'hooks', value: 10 },
      ],
    },
    {
      name: 'backend',
      children: [
        { name: 'api', value: 25 },
        { name: 'services', value: 15 },
        { name: 'models', value: 10 },
      ],
    },
    {
      name: 'docs',
      value: 15,
      children: [
        { name: 'guides', value: 10 },
        { name: 'reference', value: 5 },
      ],
    },
  ],
  pulse: [
    { user: 'alice', action: 'opened PR #123', time: new Date().toISOString(), type: 'pr' },
    {
      user: 'bob',
      action: 'commented on issue #45',
      time: new Date().toISOString(),
      type: 'comment',
    },
    { user: 'charlie', action: 'pushed to main', time: new Date().toISOString(), type: 'push' },
  ],
  issues: [
    {
      number: 101,
      title: 'Update dependencies',
      labels: [{ name: 'good first issue', color: '7057ff' }],
      comments: 2,
      created_at: new Date().toISOString(),
      html_url: '#',
    },
    {
      number: 102,
      title: 'Fix typography in header',
      labels: [{ name: 'design', color: 'e99695' }],
      comments: 0,
      created_at: new Date().toISOString(),
      html_url: '#',
    },
    {
      number: 103,
      title: 'Add unit tests',
      labels: [{ name: 'help wanted', color: '008672' }],
      comments: 5,
      created_at: new Date().toISOString(),
      html_url: '#',
    },
  ],
  roadmap: [
    {
      id: 1,
      number: 1,
      title: 'Phase 1: Foundation',
      description: 'Core architecture setup',
      status: 'completed',
      progress: 100,
      due_on: '2025-01-01',
      open_issues: 0,
      closed_issues: 12,
      html_url: '#',
    },
    {
      id: 2,
      number: 2,
      title: 'Phase 2: UI Polish',
      description: 'Glassmorphism redesign',
      status: 'in-progress',
      progress: 80,
      due_on: '2025-02-15',
      open_issues: 5,
      closed_issues: 8,
      html_url: '#',
    },
    {
      id: 3,
      number: 3,
      title: 'Phase 3: Logic',
      description: 'Backend integration',
      status: 'planned',
      progress: 0,
      due_on: '2025-03-01',
      open_issues: 10,
      closed_issues: 0,
      html_url: '#',
    },
  ],
  missionControl: {
    stats: { total: 15, backlog: 5, in_progress: 3, done: 7 },
    items: [
      {
        id: '1',
        number: 101,
        type: 'issue',
        title: 'Update dependencies',
        status: 'Backlog',
        priority: 'Low',
        domain: 'frontend',
        assignee: { login: 'jdoe', avatar: 'https://ui-avatars.com/api/?name=John+Doe' },
        labels: ['maintenance'],
        url: '#',
        updated_at: new Date().toISOString(),
      },
      {
        id: '2',
        number: 105,
        type: 'pr',
        title: 'Implement Glassmorphism',
        status: 'In Review',
        priority: 'High',
        domain: 'ui/ux',
        assignee: { login: 'asmith', avatar: 'https://ui-avatars.com/api/?name=Alice+Smith' },
        labels: ['design', 'enhancement'],
        url: '#',
        updated_at: new Date().toISOString(),
      },
      {
        id: '3',
        number: 108,
        type: 'issue',
        title: 'Fix API rate limiting',
        status: 'In Progress',
        priority: 'High',
        domain: 'backend',
        assignee: { login: 'ckent', avatar: 'https://ui-avatars.com/api/?name=Clark+Kent' },
        labels: ['bug', 'urgent'],
        url: '#',
        updated_at: new Date().toISOString(),
      },
      {
        id: '4',
        number: 112,
        type: 'pr',
        title: 'Add unit tests for auth',
        status: 'Done',
        priority: 'Normal',
        domain: 'tests',
        assignee: { login: 'bwayne', avatar: 'https://ui-avatars.com/api/?name=Bruce+Wayne' },
        labels: ['testing'],
        url: '#',
        updated_at: new Date().toISOString(),
      },
      {
        id: '5',
        number: 115,
        type: 'issue',
        title: 'Refactor Mission Control',
        status: 'Ready',
        priority: 'Normal',
        domain: 'frontend',
        assignee: null,
        labels: ['refactor'],
        url: '#',
        updated_at: new Date().toISOString(),
      },
    ],
  },
};
